services:
    filesystem:
        container_name: filesystem-mcp
        build:
            context: .
            dockerfile: src/filesystem/Dockerfile
        pull_policy: build
        volumes:
            - "C:/Users/Devat/knowledge-base/class:/class"
        restart: unless-stopped
        stdin_open: true
        tty: true
        networks:
            - mcp-network
    # time:
    #     container_name: time-mcp
    #     build:
    #         context: src/time
    #         dockerfile: Dockerfile
    #     pull_policy: build
    #     restart: unless-stopped
    #     stdin_open: true
    #     tty: true
    #     networks:
    #         - mcp-network

networks:
    default:
        driver: bridge
    mcp-network:
        external: true
